version: '2'
services:
  db:
    image: mongo:3.4
    #no mongoose ele já expoe a porta automáticamente para o containerdo
  backend:
    image: node:8.1
    volumes:
      - ./backend:/backend
    ports:
      - 3000:3000
    command: bash -c "cd /backend && npm i && node app"
  frontend:
    image: nginx:1.13
    volumes:
      - ./frontend:/usr/share/nginx/html/
    ports:
      - 91:80  

# Após configurado o docker-compose, será executado a instrução docker-compose up